### ISSUE TITLE
On recent release of esp v3.0.0.alpha board manager throwing some error due to vorbis decoder

### ISSUE THREAD

**Issue by TheZeroHz** [schreibfaul1/ESP32-audioI2S#599]
(Tested in both Arduino IDE 2.2.1 &1.8.12)
It is working well on esp v2.0.14......
However here is the error log

c:\Users\ither\OneDrive\Documents\Arduino\libraries\ESP32-audioI2S-master\src\vorbis_decoder\vorbis_decoder.cpp: In function 'int vorbis_dsp_pcmout(int32_t*, int)':
c:\Users\ither\OneDrive\Documents\Arduino\libraries\ESP32-audioI2S-master\src\vorbis_decoder\vorbis_decoder.cpp:3034:85: error: invalid conversion from 'int32_t*' {aka 'long int*'} to 'int*' [-fpermissive]
 3034 |                                 s_dsp_state->lW, s_dsp_state->W, s_dsp_state->work[i],
      |                                                                  ~~~~~~~~~~~~~~~~~~~^
      |                                                                                     |
      |                                                                                     int32_t* {aka long int*}
c:\Users\ither\OneDrive\Documents\Arduino\libraries\ESP32-audioI2S-master\src\vorbis_decoder\vorbis_decoder.cpp:3035:57: error: invalid conversion from 'int32_t*' {aka 'long int*'} to 'int*' [-fpermissive]
 3035 |                                 s_dsp_state->mdctright[i], _vorbis_window(s_blocksizes[0] >> 1),
      |                                 ~~~~~~~~~~~~~~~~~~~~~~~~^
      |                                                         |
      |                                                         int32_t* {aka long int*}
c:\Users\ither\OneDrive\Documents\Arduino\libraries\ESP32-audioI2S-master\src\vorbis_decoder\vorbis_decoder.cpp:3035:74: error: invalid conversion from 'int32_t*' {aka 'long int*'} to 'const int*' [-fpermissive]
 3035 |                                 s_dsp_state->mdctright[i], _vorbis_window(s_blocksizes[0] >> 1),
      |                                                            ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
      |                                                                          |
      |                                                                          int32_t* {aka long int*}
c:\Users\ither\OneDrive\Documents\Arduino\libraries\ESP32-audioI2S-master\src\vorbis_decoder\vorbis_decoder.cpp:3036:47: error: invalid conversion from 'int32_t*' {aka 'long int*'} to 'const int*' [-fpermissive]
 3036 |                                 _vorbis_window(s_blocksizes[1] >> 1),
      |                                 ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
      |                                               |
      |                                               int32_t* {aka long int*}
c:\Users\ither\OneDrive\Documents\Arduino\libraries\ESP32-audioI2S-master\src\vorbis_decoder\vorbis_decoder.cpp:3037:41: error: cannot convert 'int32_t*' {aka 'long int*'} to 'short int*'
 3037 |                                 outBuff + i, s_vorbisChannels,
      |                                 ~~~~~~~~^~~
      |                                         |
      |                                         int32_t* {aka long int*}
In file included from c:\Users\ither\OneDrive\Documents\Arduino\libraries\ESP32-audioI2S-master\src\vorbis_decoder\vorbis_decoder.cpp:23:
c:\Users\ither\OneDrive\Documents\Arduino\libraries\ESP32-audioI2S-master\src\vorbis_decoder\vorbis_decoder.h:264:119: note:   initializing argument 9 of 'void mdct_unroll_lap(int, int, int, int, int*, int*, const int*, const int*, short int*, int, int, int)'
  264 | void     mdct_unroll_lap(int n0, int n1, int lW, int W, int *in, int *right, const int *w0, const int *w1, short int *out,
      |                                                                                                            ~~~~~~~~~~~^~~
Multiple libraries were found for "SD.h"
  Used: C:\Users\ither\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.0-alpha1\libraries\SD
  Not used: C:\Users\ither\AppData\Local\Arduino15\libraries\SD
exit status 1

Compilation error: exit status 1

**Comment by schreibfaul1** [comment]
That was not quite it yet. I have created a new branch (Arduino-V3.0) that compiles without errors.
